### ISSUE TITLE
Making the game windowed didn't fix any problems

### ISSUE THREAD

**Issue by Popedigoz** [chreden/trawindowed#19]
Game in question: Legend (on W11). 

1) My cursor is still locked to the game, I can't freely move my cursor to my external monitor unless I Windows+D.
2) Windowed mode is useless with title bar, aka not borderless

At least ALT+TABbing is instant and does not take 15 seconds. 

Guess I can't multi-task while playing this game.

**Comment by chreden** [comment]
F8 should toggle mouse capture, does that work? There are a few keyboard shortcuts listed in the readme for the repository

**Comment by Popedigoz** [comment]
> F8 should toggle mouse capture, does that work? There are a few keyboard shortcuts listed in the readme for the repository. F5 toggles the border.

Oh wow, they do work. Thanks! Sorry for my ignorance, didn't really read it that far, my bad.
