### ISSUE TITLE
SteamDeck - Skip F5 press need (.ini) to go borderless

### ISSUE THREAD

**Issue by Klemci** [chreden/trawindowed#20]
Hello,

i'd like to use the DLL but i could only if it had an ini/setting to tell it in which mode to start without the need to press F5 (each game's launch), on Steam-Deck there is no keyboard, that, thanks.

**Comment by chreden** [comment]
Ah, I didn't think about devices that didn't have a keyboard. I'll see what I can do.

**Comment by Klemci** [comment]
Well, that's good news, thanks, i know it  works, but i had to popup the soft keyboard then change it to another type (small has no FN/F1-12 keys) so i'm happy i will be able to use use it, it was too much just to launch a game.

**Comment by Klemci** [comment]
Now that i think about it, you can skip the ini idea, and just make different version that start in different mode by default, Fullscreen, Windowd & Borderless, perhaps it's easyer :p

**Comment by chreden** [comment]
I've added a check for a `-borderless` command line argument. If you set it in Launch Options in Steam it should start borderless. There's a release binary [here](https://github.com/chreden/trawindowed/releases/tag/v1.5.0) if you want to try it.

**Comment by Klemci** [comment]
Oh yeah, it worked, thanks. TRA on SteamDeck is more enjoyable graphically (even with the unoficial texpack mod).
