### ISSUE TITLE
Window is always on top

### ISSUE THREAD

**Issue by darrenmason** [chreden/trawindowed#7]
This may be just a setting I am missing, but I am finding the TRA window to be always on top.  Is there an option to disable this?

**Comment by chreden** [comment]
It's not something I did on purpose, most likely the game window is created with WS_EX_TOPMOST. I can look at adding an option to toggle this with another F key.

**Comment by chreden** [comment]
This is in https://github.com/chreden/trawindowed/releases/tag/v1.2.0
